# RabbitMq url: http://localhost:15672/
# username: guest, password: guest

version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - c:/data/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - c:/data/rabbitmq/log/:/var/log/rabbitmq
