# RabbitMq url: http://localhost:15672/
# username: guest, password: guest

version: "3.2"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - c:/data/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - c:/data/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - discord-clash

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: discordClash
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - C:/data/mongo/db:/data/db
      - C:/data/mongo/configdb:/data/configdb
    networks:
      - discord-clash

networks:
  discord-clash:
    driver: bridge
