@startuml
skinparam defaultFontName Muli

title **Discord Clash - Diagram komponentów**

frame "Aplikacja serwerowa" {
    [API]
}

frame "Aplikacja konsolowa" {
    [System Rekomendacji] as RS  
}

frame "MongoDB" {
    database "Baza użytkowników" as DB2
    database "Baza wydarzeń" as DB3
}

frame "MSSQL" {
    database "Model rekomendacji" as DB1
}

frame RabbitMQ as Rabbit {
    queue "Kolejka" as Q1
}

frame "Aplikacja konsolowa\n - usługa" {
    [Discord BOT] as BOT
}

() "Serwer Discord" as Channel

API -right-> Q1 : "\tpublikuje\t"
Q1 -right-> BOT : ""
Q1 <.right. BOT : "\tsubskrybuje\t"
BOT -right-> Channel : "\t"
RS -up-> DB1
API --> DB1
API --> DB2
API --> DB3

@enduml