@startuml
skinparam defaultFontName Muli

title Discord Clash - Diagram komponentów

package "Aplikacja serwerowa" {
    [API]
    [System Rekomendacji] as RS  
}

[Discord BOT] as BOT
() "Kanał na serwerze" as Kanal

database "MSSQL" {
    [Baza użytkowników] as DB1
    [Baza wydarzeń] as DB2
}

Kanal ..> [BOT]
[BOT] - [API]
[API] ..> [RS]
[API] -up-> DB1
[API] -up-> DB2

@enduml